/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-background": "#111c2c",
          "surface-container": "#e7eeff",
          "inverse-on-surface": "#ebf1ff",
          "on-secondary-fixed-variant": "#00504e",
          "surface-bright": "#f9f9ff",
          "surface-tint": "#2d6197",
          "surface": "#f9f9ff",
          "primary": "#00355f",
          "on-primary-fixed": "#001c37",
          "secondary-fixed-dim": "#78d6d2",
          "on-secondary-container": "#006e6c",
          "background": "#f9f9ff",
          "surface-container-low": "#f0f3ff",
          "on-error-container": "#93000a",
          "secondary-container": "#91f0ec",
          "tertiary-container": "#434c4d",
          "on-tertiary-container": "#b3bcbd",
          "inverse-surface": "#263142",
          "surface-variant": "#d8e3fa",
          "surface-dim": "#cfdaf1",
          "on-secondary-fixed": "#00201f",
          "inverse-primary": "#a0c9ff",
          "tertiary": "#2d3536",
          "on-surface": "#111c2c",
          "on-error": "#ffffff",
          "tertiary-fixed-dim": "#bfc8c9",
          "on-primary-fixed-variant": "#07497d",
          "on-tertiary-fixed-variant": "#404849",
          "on-surface-variant": "#42474f",
          "error": "#ba1a1a",
          "on-secondary": "#ffffff",
          "secondary": "#006a68",
          "primary-fixed": "#d2e4ff",
          "surface-container-highest": "#d8e3fa",
          "on-primary-container": "#8ebdf9",
          "on-tertiary": "#ffffff",
          "on-tertiary-fixed": "#151d1e",
          "outline": "#727780",
          "primary-fixed-dim": "#a0c9ff",
          "tertiary-fixed": "#dbe4e5",
          "on-primary": "#ffffff",
          "primary-container": "#0f4c81",
          "error-container": "#ffdad6",
          "secondary-fixed": "#94f2ef",
          "surface-container-high": "#dee8ff",
          "outline-variant": "#c2c7d1",
          "surface-container-lowest": "#ffffff"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "section-gap": "80px",
          "gutter": "24px",
          "container-max": "1280px",
          "margin-mobile": "16px",
          "base": "8px"
      },
      "fontFamily": {
          "label-sm": ["Inter", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "headline-lg-mobile": ["Manrope", "sans-serif"],
          "headline-md": ["Manrope", "sans-serif"],
          "headline-lg": ["Manrope", "sans-serif"],
          "body-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "label-sm": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
          "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
          "headline-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
          "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
          "headline-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
